sentence_retrieval:
    1_scale_prob: 0.05
    1_top_k: 5
    nn_doc_threshold: 0.00001
    nn_doc_top_k: 10
    sent_prob_for_2doc: 0.1
    sent_topk_for_2doc: 5
    sentence_2_scale_prob: 0.9
    sent_2_top_k: 1
    enhance_1_scale_prob: -1
    build_submission: True
document_retrieval:
    method: pageview
folder_structure:
    root_path: '/home/bmelman/C_disk/02_university/06_thesis/01_code/02_NSMN/combine-FEVER-NSMN'
    src: 
        document_retrieval: 01_document_retrieval
        sentence_retrieval: 02_sentence_retrieval
        inference: 03_inference
steps:
    s1_tokenizing: 
        do: False
        out_file: /home/bmelman/C_disk/02_university/06_thesis/01_code/02_NSMN/combine-FEVER-NSMN/_04_results/pipeline_r_aaai_doc/2019_05_20_12:36:14_r/t_shared_task_dev.jsonl
    s2_1doc_retri:
        do: True
        out_file: _und_
    s2_2_1doc_nn_retri:
        do: True
        out_file: _und_
    s3.1sen_select:
        do: True
        out_file: _und_
    s4_2doc_retri:
        do: True
        out_file: _und_
    s5_2sen_select:
        do: True
        out_file: _und_
    s6_nli:
        do: True
        out_file: config.RESULT_PATH / pipeline_r_aaai_doc/2018_09_02_17:11:42_r/nli_r_shared_task_dev_no_doc_scale:0.05.jsonl



